# Generated by Django 4.2.2 on 2023-06-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0002_local_rename_camada_stock_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='item',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
