# Generated by Django 4.2.2 on 2023-07-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0005_producto_cliente_date_created_ordenar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ordenar',
            name='tags',
            field=models.ManyToManyField(to='Roel.tag'),
        ),
    ]
