# Generated by Django 4.2.2 on 2023-07-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0006_tag_ordenar_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenar',
            name='tags',
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(to='Roel.tag'),
        ),
    ]
