# Generated by Django 4.2.2 on 2023-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0007_remove_ordenar_tags_producto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Pulsera', 'Pulsera'), ('Collar', 'Collar'), ('Pendiente', 'Pendiente'), ('Pañuelo', 'Pañuelo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
