# Generated by Django 4.2.2 on 2023-07-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0010_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='distribuidora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Roel.distribuidora'),
        ),
    ]
