# Generated by Django 4.2.2 on 2023-07-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0011_producto_distribuidora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidora',
            name='apellido',
        ),
    ]
