# Generated by Django 4.2.2 on 2023-07-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0014_solicituddistribuidora'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenar',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordenar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenar',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('No se puede entregar', 'No se puede entregar'), ('Entregado', 'Entregado')], max_length=200, null=True),
        ),
    ]
