# Generated by Django 4.2.2 on 2023-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0015_ordenar_precio_alter_ordenar_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Pulsera', 'Pulsera'), ('Collar', 'Collar'), ('Pendiente', 'Pendiente'), ('Electrodomestico', 'Electrodomestico'), ('Mueble', 'Mueble'), ('Focos', 'Focos'), ('Comestibles', 'Comestibles'), ('Componente PC', 'Componente PC'), ('Producto de belleza', 'Producto de belleza')], max_length=200, null=True),
        ),
    ]
