# Generated by Django 4.2.2 on 2023-08-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0016_producto_cantidad_stock_alter_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
