# Generated by Django 4.2.2 on 2023-08-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0017_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenar',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
