# Generated by Django 4.2.2 on 2023-08-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roel', '0018_ordenar_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
    ]
